# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0003_auto_20171012_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'permissions': (('Puede crear Alquileres', 'add_alquiler'),)},
        ),
    ]
