# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0004_auto_20171015_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'permissions': (('add_alquileres', 'Puede crear Alquileres'),)},
        ),
    ]
