# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0007_auto_20171015_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carnet',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
