# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0009_alquiler_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='pagado',
            field=models.BooleanField(default=True),
        ),
    ]
