# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0010_alquiler_pagado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquiler',
            old_name='vehiculos',
            new_name='vehiculo',
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
