# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 19:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0012_alquiler_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='exceso',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
