# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0013_auto_20171024_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
