# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alquiler', '0014_auto_20171024_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='exceso',
            field=models.CharField(max_length=100),
        ),
    ]
