# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 04:05
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('distancia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
            ],
        ),
    ]
