# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ubicacion', '0002_limite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limite',
            old_name='distancia',
            new_name='distancia_km',
        ),
    ]
